/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._web_22dinf._pages._web._cn._payment;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.trendy.fw.common.util.StatusKit;
import com.trendy.fw.common.util.MapKit;
import com.trendy.ow.portal.payment.config.PayConfig;
import com.trendy.ow.portal.payment.bean.PayCompanyInfoBean;
import com.trendy.ow.portal.payment.bean.PayChannelInfoBean;
import com.trendy.ow.portal.payment.bean.PayInfoBean;
import com.trendy.ow.portal.payment.bean.PayRequestBean;
import java.util.Map.Entry;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.*;

public class _paychannellist__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;

  
  Map<String, String> _skuYear =  new HashMap<String, String>();


  
  public String imgUrl = "http://static.lpmas.com/images/trendy/";
  
  public Boolean _isTestSite(String url) {
  	if (url.indexOf("test.") >= 0) {
  		return true;
  	}
  	else {
  		return false;
  	}
  }
  
  public String _getBrandDomain(String currUrl) {
  	if (currUrl.indexOf("lpmas.com") >= 0) return ".lpmas.com";
  	return "";
  }
  
  public String _getBrandName(String currUrl) {
  	if (currUrl.indexOf("lpmas.com") >= 0) return "lpmas";
  	return "";
  }
  
  public String _getSiteName(String currUrl, String siteType) {
  	String test = _isTestSite(currUrl) ? "test." : "";
  	String domain = _getBrandDomain(currUrl);
  	if (siteType == "img2") test = "";
  	return "//" + test + siteType + domain;
  }
  
  public String getImgPath(String sku, String imgSize, String imgType) {
  	String url = "";
  	return url;
  }
  
  public String getBrand(String sku) {
  	return "";
  }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    
Map _sName = new HashMap();
	_sName.put("_siteServerName",request.getServerName());
	_sName.put("www", _getSiteName(request.getServerName(), "www"));
	_sName.put("my", _getSiteName(request.getServerName(), "my"));
	_sName.put("passport", _getSiteName(request.getServerName(), "passport"));
	_sName.put("act", _getSiteName(request.getServerName(), "act"));
	_sName.put("pay", _getSiteName(request.getServerName(), "pay"));
	_sName.put("img2", _getSiteName(request.getServerName(), "static"));

    
	PayRequestBean detailBean=(PayRequestBean)request.getAttribute("payRequestBean");
	 //  PayInfoBean payInfoBean=(PayInfoBean)request.getAttribute("PayInfoBean");
	   Map<Integer, List<PayChannelInfoBean>> map=( Map<Integer, List<PayChannelInfoBean>>)request.getAttribute("channelListGroupByType");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    out.print((detailBean.getInfoId()));
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((detailBean.getInfoId()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((request.getAttribute("payId")));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((detailBean.getAppId() ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((map.keySet().size() ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((request.getAttribute("payId")));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    
							Set<Entry<Integer,List<PayChannelInfoBean>>> entrys=map.entrySet();
							for(Entry<Integer,List<PayChannelInfoBean>> entry:entrys){
							
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((MapKit.getValueFromMap(entry.getKey()+"", StatusKit.toMap(PayConfig.PAY_CHANNEL_TYPE_LIST))));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    
								List<PayChannelInfoBean> list=entry.getValue();
								for(PayChannelInfoBean channel:list){	
								
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((_sName.get("img2")));
    out.print((channel.getChannelLogo() ));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    
								}
								
    out.write(_jsp_string17, 0, _jsp_string17.length);
    
							}
							
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string20, 0, _jsp_string20.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/web/cn/payment/PayChannelList.jsp"), 4089082715133811615L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/Common.jsp"), -1387744430836111862L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("module/static/3c/ed/my_css_js.html"), 6432780355486831806L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("module/static/da/89/och_header_v1.html"), 6505114894531017549L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("module/static/b4/69/och_footer_v1.html"), 3214331617896480241L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string18;
  private final static char []_jsp_string13;
  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string15;
  private final static char []_jsp_string11;
  private final static char []_jsp_string16;
  private final static char []_jsp_string0;
  private final static char []_jsp_string2;
  private final static char []_jsp_string5;
  private final static char []_jsp_string12;
  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string19;
  private final static char []_jsp_string17;
  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string20;
  private final static char []_jsp_string14;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  static {
    _jsp_string18 = "\r\n						</div>\r\n					</div>	\r\n				</div>\r\n				<script>\r\n					te$.ui.switching.init('orderListTab');\r\n				</script>\r\n				<div class=\"pay_total col_13\">\r\n					<div>\r\n						<em>\r\n							\u4f7f\u7528\r\n							<span>\r\n								<img id=\"imgPayChannel\" src=\"\" />\r\n								<i>*</i>\r\n							</span>\r\n						</em>\r\n						\u652f\u4ed8 <b>\uffe5".toCharArray();
    _jsp_string13 = "\">\r\n										<input type=\"radio\" name=\"payChannel\" value=\"".toCharArray();
    _jsp_string10 = "\r\n							<div class=\"pay_bank_list\">\r\n\r\n								<!--".toCharArray();
    _jsp_string8 = "\u5143</b>\uff0c\u8bf7\u9009\u62e9\uff1a</p>\r\n				<form action=\"PayRedirect.do\" id=\"payForm\">\r\n					<input type=\"hidden\" name=\"payId\" value=\"".toCharArray();
    _jsp_string15 = "\" />\r\n										<img src=\"http:".toCharArray();
    _jsp_string11 = "-->\r\n								".toCharArray();
    _jsp_string16 = "\" />\r\n										<span>*</span>\r\n									</label>\r\n								</p>\r\n								".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n	<meta charset=\"utf-8\">\r\n	<title>\u9009\u62e9\u652f\u4ed8\u65b9\u5f0f</title>\r\n\r\n		<meta name=\"renderer\" content=\"webkit\">\r\n	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n	<link rel=\"stylesheet\" href=\"http://img2.ochirly.com.cn/rs/common/v1/web/css/my.min.css\" />\r\n\r\n	<script src=\"http://img2.ochirly.com.cn/rs/lib/js/jquery.js\"></script>\r\n	<script src=\"http://img2.ochirly.com.cn/rs/common/v1/web/js/my.min.js\"></script>	\r\n</head>\r\n<body>\r\n	<script>\r\n		te$.setMyStyle();\r\n	</script>\r\n\r\n	<div class=\"header\">\r\n		<h1 class=\"logo\" id=\"myLogo\"></h1>\r\n\r\n		<div class=\"top_link_box\">\r\n			<!-- <a href=\"#\" class=\"link_langu\"><span>\u4e2d\u56fd</span></a> -->\r\n			<span id=\"paramLogin\"><a href=\"\" id=\"linkLogin\">\u767b\u5f55\u2502\u6ce8\u518c</a></span>\r\n			<a href=\"#\" id=\"linkAccount\">\u6211\u7684\u8d26\u6237</a>\r\n			<a href=\"javascript:;\" class=\"link_Wishlist\"  id=\"linkWishlist\">\u6211\u7684\u6536\u85cf</a>\r\n			<a href=\"#\" class=\"link_bag\" id=\"linkCart\">\u8d2d\u7269\u888b(<span id=\"cartNum\">0</span>)</a>\r\n		</div>\r\n		<div class=\"search2013\" id=\"navSearch\" style=\"display:none;\">\r\n			<input type=\"text\" value=\"\u641c\u7d22\u60a8\u611f\u5174\u8da3\u7684\u5185\u5bb9\" id=\"navIntSearch\">	\r\n			<button type=\"button\">\u641c\u7d22</button>\r\n		</div>\r\n	</div>\r\n	<script>\r\n		var _mvq = _mvq || [];\r\n		var _gaSkuItem = _gaSkuItem || [];\r\n		_mvq.push(['$setGeneral', 'ordercreate', '', '', '']);\r\n		_mvq.push(['$addOrder','".toCharArray();
    _jsp_string2 = "']);\r\n	</script>	\r\n	<div class=\"cart_container\">\r\n		<div class=\"edge\">\r\n			<div class=\"checkout_step\">\r\n				<div class=\"pay_tip col_6\">\r\n					<h2>\u8ba2\u5355\u5df2\u751f\u6210\uff0c\u8bf7\u7ee7\u7eed\u5b8c\u6210\u652f\u4ed8\uff01</h2>\r\n					<p><span>\u8ba2\u5355\u7f16\u53f7\uff1a".toCharArray();
    _jsp_string5 = " ;appId:".toCharArray();
    _jsp_string12 = "\r\n								<p>\r\n									<label for=\"raBank".toCharArray();
    _jsp_string6 = "-->\r\n				<!-- <div>\u663e\u793a\u6e20\u9053|\u6e20\u9053\u516c\u53f8\u6570\u76ee\uff1a".toCharArray();
    _jsp_string3 = "</span> <span>\u652f\u4ed8\u91d1\u989d\uff1a<b>\uffe5".toCharArray();
    _jsp_string19 = "</b>\r\n					</div>\r\n					<p>\r\n						<button class=\"col_3\" type=\"button\" id=\"btnGotoPay\">\u652f\u4ed8</button>\r\n					</p>\r\n				</div>\r\n				\r\n			</div>\r\n		</div>\r\n	</div>\r\n	<script>\r\n		var _gaOrderInfo = {\r\n			'shop' : te$.getCurrBrand(),\r\n			'total': ".toCharArray();
    _jsp_string17 = "\r\n							</div>\r\n							".toCharArray();
    _jsp_string7 = "  </div> -->\r\n				<p class=\"pay_tip_fallow\">\u4f60\u9700\u8981\u652f\u4ed8\uff1a<b>\uffe5".toCharArray();
    _jsp_string9 = "\" />\r\n					<input type=\"hidden\" name=\"channelId\" value=\"\" />\r\n				</form>\r\n				<div class=\"pay_choose col_13\">\r\n					<div class=\"pay_choose_content\" id=\"payChannelChoose\">\r\n						<ul class=\"tab order_list_tab\" id=\"orderListTab\" data-config=\"{'target':'payWayList', 'tab':'li', 'content':'div', 'activeTabClass':'active', 'activeContentClass':''}\">\r\n							<li class=\"active col_4_1 cell\"><span>\u7f51\u4e0a\u94f6\u884c\u652f\u4ed8</span></li>\r\n							<li class=\"col_4_1 cell\"><span>\u7f51\u4e0a\u652f\u4ed8\u5e73\u53f0</span></li>\r\n						</ul>\r\n						<div id=\"payWayList\">\r\n							".toCharArray();
    _jsp_string20 = ",\r\n			'ship': 0.00000,\r\n			'id' : 5585244\r\n		}\r\n		var _gaViewPoint1 = 'beforePay';\r\n		te$.business.pay.initPayChannel();\r\n	</script>\r\n\r\n<div class=\"copyright\">\r\n	<div class=\"copyright_inner\" id=\"myFooter\">\r\n		<p class=\"copyright_links\" id=\"myCopyrightLinks\">\r\n			<a href=\"#\">\u9690\u79c1\u7533\u660e</a>\r\n			<a href=\"#\">\u8054\u7cfb\u6211\u4eec</a>\r\n		</p>\r\n		<p class=\"copyright_links copyright_txt\">Copyright @ 2010-<em id=\"copyrightYear\"></em> \u5e7f\u5dde\u8d6b\u57fa\u4fe1\u606f\u79d1\u6280\u6709\u9650\u516c\u53f8\u7248\u6743\u6240\u6709  \u589e\u503c\u7535\u4fe1\u4e1a\u52a1\u7ecf\u8425\u8bb8\u53ef\u8bc1 <a href=\"http://www.miibeian.gov.cn/\" id=\"linkIcp\" target=\"_blank\">\u7ca4B2-20100553 \u7ca4ICP\u590710229258-<span id=\"icpNum\">1</span>\u53f7</a></p>\r\n	</div>\r\n</div>\r\n<script>\r\n	te$.system.setMyHeadAndFooter();\r\n	te$.system.hasLoad();\r\n</script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string14 = "\" id=\"raBank".toCharArray();
    _jsp_string4 = "</b></span></p>\r\n				</div>\r\n			</div>\r\n\r\n			<div class=\"checkout row\">\r\n				<!--\u652f\u4ed8\u4fe1\u606f|\u652f\u4ed8Id: ".toCharArray();
    _jsp_string1 = "', '".toCharArray();
  }
}
