/*
 * JSP generated by Resin Professional 4.0.44 (built Wed, 22 Apr 2015 02:04:40 PDT)
 */

package _jsp._web_22dinf._pages._wap._cn._payment;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.trendy.fw.common.util.StatusKit;
import com.trendy.fw.common.util.MapKit;
import com.trendy.ow.portal.payment.config.PayConfig;
import com.trendy.ow.portal.payment.bean.PayCompanyInfoBean;
import com.trendy.ow.portal.payment.bean.PayChannelInfoBean;
import com.trendy.ow.portal.payment.bean.PayInfoBean;
import com.trendy.ow.portal.payment.bean.PayRequestBean;
import java.util.Map.Entry;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.*;

public class _paychannellist__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;

  
  Map<String, String> _skuYear =  new HashMap<String, String>();


  
  public String imgUrl = "http://static.lpmas.com/images/trendy/";
  
  public Boolean _isTestSite(String url) {
  	if (url.indexOf("test.") >= 0) {
  		return true;
  	}
  	else {
  		return false;
  	}
  }
  
  public String _getBrandDomain(String currUrl) {
  	if (currUrl.indexOf("lpmas.com") >= 0) return ".lpmas.com";
  	return "";
  }
  
  public String _getBrandName(String currUrl) {
  	if (currUrl.indexOf("lpmas.com") >= 0) return "lpmas";
  	return "";
  }
  
  public String _getSiteName(String currUrl, String siteType) {
  	String test = _isTestSite(currUrl) ? "test." : "";
  	String domain = _getBrandDomain(currUrl);
  	if (siteType == "img2") test = "";
  	return "//" + test + siteType + domain;
  }
  
  public String getImgPath(String sku, String imgSize, String imgType) {
  	String url = "";
  	return url;
  }
  
  public String getBrand(String sku) {
  	return "";
  }

  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=utf-8");

    
Map _sName = new HashMap();
	_sName.put("_siteServerName",request.getServerName());
	_sName.put("www", _getSiteName(request.getServerName(), "www"));
	_sName.put("my", _getSiteName(request.getServerName(), "my"));
	_sName.put("passport", _getSiteName(request.getServerName(), "passport"));
	_sName.put("act", _getSiteName(request.getServerName(), "act"));
	_sName.put("pay", _getSiteName(request.getServerName(), "pay"));
	_sName.put("img2", _getSiteName(request.getServerName(), "static"));

    
	PayRequestBean detailBean=(PayRequestBean)request.getAttribute("payRequestBean");
	 //  PayInfoBean payInfoBean=(PayInfoBean)request.getAttribute("PayInfoBean");
	   Map<Integer, List<PayChannelInfoBean>> map=( Map<Integer, List<PayChannelInfoBean>>)request.getAttribute("channelListGroupByType");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    out.print((_sName.get("my")));
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((_sName.get("my")));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((_sName.get("my")));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((detailBean.getInfoId()));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((detailBean.getInfoId()));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((request.getAttribute("payId")));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((detailBean.getAppId() ));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((map.keySet().size() ));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((request.getAttribute("payId")));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    
						Set<Entry<Integer,List<PayChannelInfoBean>>> entrys=map.entrySet();
						for(Entry<Integer,List<PayChannelInfoBean>> entry:entrys){
						
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((MapKit.getValueFromMap(entry.getKey()+"", StatusKit.toMap(PayConfig.PAY_CHANNEL_TYPE_LIST))));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    
							List<PayChannelInfoBean> list=entry.getValue();
							for(PayChannelInfoBean channel:list){	
							
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((_sName.get("img2")));
    out.print((channel.getChannelLogo() ));
    out.write(_jsp_string15, 0, _jsp_string15.length);
    out.print((map.keySet().size()==1?"choose":"no_choose"));
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string19, 0, _jsp_string19.length);
    out.print((map.keySet().size()==1?"checked":""));
    out.write(_jsp_string20, 0, _jsp_string20.length);
    if(map.keySet().size()==1){
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((channel.getChannelId() ));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    }
    out.write(_jsp_string23, 0, _jsp_string23.length);
    
							}
						}
						
    out.write(_jsp_string24, 0, _jsp_string24.length);
    out.print((String.format("%.2f", detailBean.getRequestAmount())));
    out.write(_jsp_string25, 0, _jsp_string25.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7371470110589488364L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/wap/cn/payment/PayChannelList.jsp"), 4410185465615361422L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/pages/include/Common.jsp"), -1387744430836111862L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("module/static/30/ca/lp_ec_meta.html"), 421548456982626800L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("module/static/cc/12/lp_ec_common.html"), 4907170295825755559L, false);
    _caucho_depends.add(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string12;
  private final static char []_jsp_string19;
  private final static char []_jsp_string23;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string7;
  private final static char []_jsp_string10;
  private final static char []_jsp_string3;
  private final static char []_jsp_string15;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string24;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string25;
  private final static char []_jsp_string22;
  private final static char []_jsp_string13;
  private final static char []_jsp_string17;
  private final static char []_jsp_string16;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string20;
  private final static char []_jsp_string21;
  private final static char []_jsp_string14;
  private final static char []_jsp_string2;
  static {
    _jsp_string5 = "']);\r\n		</script>\r\n		\r\n\r\n		<div class=\"back_c10 pa1\">\r\n		    <div class=\"c_3 f_w s_fs1 pa11\">\r\n		            <p class=\"dis\">\r\n		                <span>\u8ba2\u5355\u7f16\u53f7\uff1a</span><span>".toCharArray();
    _jsp_string12 = "\r\n							<!--".toCharArray();
    _jsp_string19 = "\" ".toCharArray();
    _jsp_string23 = "\r\n					        </p>\r\n							".toCharArray();
    _jsp_string6 = "</span>\r\n		            </p>\r\n		            <p class=\"dis fr\">\r\n		                <span class=\"c_2\">\uffe5".toCharArray();
    _jsp_string8 = " ;appId:".toCharArray();
    _jsp_string7 = "</span>\r\n		            </p>\r\n		    </div>\r\n			<!--\u652f\u4ed8\u4fe1\u606f|\u652f\u4ed8Id: ".toCharArray();
    _jsp_string10 = "  </div> -->\r\n			<form action=\"PayRedirect.do\" id=\"payForm\">\r\n				<input type=\"hidden\" name=\"payId\" value=\"".toCharArray();
    _jsp_string3 = "/order/cart.do\"><img src=\"/lpmas/ec/wap/v0/images/key.png\" class=\"fr\"></a>\r\n		    <div class=\"shop_tnum\">\r\n		        <span class=\"red_point border-r1\"></span>\r\n		    </div>\r\n		</header>\r\n        \r\n        <script>\r\n			var _mvq = _mvq || [];\r\n			var _gaSkuItem = _gaSkuItem || [];\r\n			_mvq.push(['$setGeneral', 'ordercreate', '', '', '']);\r\n			_mvq.push(['$addOrder','".toCharArray();
    _jsp_string15 = "\" class=\"pay_img\">\r\n					            <span class=\"chose_img ".toCharArray();
    _jsp_string9 = "-->\r\n			<!-- <div>\u663e\u793a\u6e20\u9053|\u6e20\u9053\u516c\u53f8\u6570\u76ee\uff1a".toCharArray();
    _jsp_string11 = "\" />\r\n				<input type=\"hidden\" name=\"channelId\" value=\"\" />\r\n			</form>\r\n			\r\n		    <p class=\"clear\"></p>\r\n		    <div id=\"payChannelChoose\">\r\n		        <p class=\"c_3 s_fs pa11 bot\">\u9009\u62e9\u652f\u4ed8\u65b9\u5f0f</p>\r\n		        \r\n						".toCharArray();
    _jsp_string24 = "\r\n		    </div>\r\n		</div>\r\n		\r\n		<div class=\"pay_btn\"><p class=\"u_btn go_pay border-r w9\" id=\"btnGotoPay\">\u652f\u4ed8</p></div>\r\n\r\n	<script>\r\n		var _gaOrderInfo = {\r\n			'shop' : te$.getCurrBrand(),\r\n			'total': ".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html>\r\n<html lang=\"en\">\r\n    <head>\r\n            <meta charset=\"UTF-8\">\r\n    <meta content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\" name=\"viewport\" />\r\n   <meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7, IE=9\" />\r\n        <title>\u9009\u62e9\u652f\u4ed8\u65b9\u5f0f</title>\r\n        \r\n    <link rel=\"stylesheet\" href=\"/lpmas/ec/wap/v0/css/base.css\" type=\"text/css\">\r\n    <link rel=\"stylesheet\" href=\"/lpmas/ec/wap/v0/css/style.css\" type=\"text/css\">\r\n    <script src=\"/lpmas/ec/wap/v0/js/jquery-1.8.3.js\" type=\"text/javascript\"></script>\r\n    <script src=\"/lpmas/ec/wap/v0/js/common.js\" type=\"text/javascript\"></script>\r\n        <script src=\"/lpmas/ec/common/js/te.js\"></script>\r\n		<script src=\"/lpmas/ec/common/js/te.business.js\"></script>\r\n    </head>\r\n<body class=\"body_bg\">\r\n		<header class=\"box-s\">\r\n			<a href =\"".toCharArray();
    _jsp_string1 = "/order/list.do?status=0\"><img src=\"/lpmas/ec/wap/v0/images/point.png\" class=\"fl point_img\"></a>\r\n		    <span class=\"head_title\">\u9009\u62e9\u652f\u4ed8\u65b9\u5f0f</span>\r\n		    <a href=\"".toCharArray();
    _jsp_string25 = ",\r\n			'ship': 0.00000,\r\n			'id' : 5585244\r\n		};\r\n		$(document).ready(function(){\r\n			var	payForm = t$('payForm'),\r\n				channelChoose = t$('payChannelChoose'),\r\n				check = null;\r\n\r\n			if (!payForm) return;\r\n\r\n			check = function() {\r\n				if (payForm.payId.value && payForm.channelId.value && payForm.channelId.value!='') return true;\r\n				else {\r\n					alert('\u8bf7\u9009\u62e9\u4e00\u79cd\u652f\u4ed8\u65b9\u5f0f');\r\n					return false;	\r\n				}\r\n			};\r\n\r\n			$('#payChannelChoose input').click(function(){\r\n				payForm.channelId.value = this.value;\r\n				$(channelChoose).find('span').each(function(){\r\n					$(this).removeClass(\"choose\").addClass(\"no_choose\");\r\n				});\r\n				$(this).prev(\"span\").removeClass(\"no_choose\").addClass(\"choose\");\r\n			});\r\n\r\n			$('#btnGotoPay').click(function(){\r\n				if (check()) payForm.submit();\r\n			});\r\n		});\r\n	</script>\r\n	\r\n</body>\r\n</html>".toCharArray();
    _jsp_string22 = "';</script>".toCharArray();
    _jsp_string13 = "-->\r\n							".toCharArray();
    _jsp_string17 = "\"></span>\r\n					            <input type=\"radio\" class=\"radio_pay\" name=\"payChannel\" value=\"".toCharArray();
    _jsp_string16 = "\" for=\"raBank".toCharArray();
    _jsp_string18 = "\" id=\"raBank".toCharArray();
    _jsp_string4 = "', '".toCharArray();
    _jsp_string20 = " />\r\n					            ".toCharArray();
    _jsp_string21 = "<script>t$('payForm').channelId.value = '".toCharArray();
    _jsp_string14 = "\r\n					        <p class=\"bot pa12 po_r\" >\r\n					            <img src=\"http:".toCharArray();
    _jsp_string2 = "/user/Home.do\"><img src=\"/lpmas/ec/wap/v0/images/user.png\" class=\"fr  shop_car right1\"></a>\r\n		    <a href=\"".toCharArray();
  }
}
